### ISSUE TITLE
Build failed if using sonar-plugin-api ver-5.5 and above

### ISSUE THREAD

**Issue by goprayogo** [iwarapter/gradle-sonar-packaging-plugin#15]
I faced a similar issue like #8 

If I am using the `sonar-plugin-api` lower than version 5.5, I faced no issue.

However, when I use plugin version 5.5 and above, i encountered the problem as described in #8. 
```

FAILURE: Build failed with an exception.
16:23:42.580 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
16:23:42.580 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
16:23:42.580 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':analyzer:pluginPackaging'.
16:23:42.580 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > org.codehaus.sonar:sonar-plugin-api or org.sonarsource.sonarqube:sonar-plugin-api should be declared in dependencies
```
Stacktrace
```
Caused by: org.gradle.api.GradleException: org.codehaus.sonar:sonar-plugin-api or org.sonarsource.sonarqube:sonar-plugin-api should be declared in dependencies
        at com.iadams.gradle.plugins.core.DependencyQuery.checkApiDependency(DependencyQuery.groovy:89)
        at com.iadams.gradle.plugins.core.DependencyQuery$checkApiDependency.call(Unknown Source)
```

**Comment by iwarapter** [comment]
I have just tested this with a simple reproducer:
```
plugins {
  id "com.iadams.sonar-packaging" version "0.1.4"
}

repositories {
  mavenCentral()
}

dependencies {
  provided 'org.sonarsource.sonarqube:sonar-plugin-api:5.6'
}

version = '1.0'

sonarPackaging {
  pluginDir = "$buildDir/myServer"
  pluginKey = 'example'
  pluginClass = 'org.sonar.plugins.sample.SamplePlugin'
  pluginName = 'Example'
  pluginDescription = 'An Example Plugin!'
}
```

```
gradle clean build
:clean
:compileJava
Note: /Users/iwarapter/IdeaProjects/gradle-sonar-packaging-plugin-tests/src/main/java/org/sonar/plugins/sample/SamplePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:processResources UP-TO-DATE
:classes
:jar
:pluginPackaging
Checking for sonar-plugin-api
-------------------------------------------------------
Plugin definition in update center
-------------------------------------------------------
Sonar Plugin Created.
:assemble
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test UP-TO-DATE
:check UP-TO-DATE
:build

BUILD SUCCESSFUL

Total time: 3.405 secs
```

Can you provide me with your build file - any more information to help me reproduce?

**Comment by goprayogo** [comment]
Hi, I used the following in my `build.gradle`


```
buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "gradle.plugin.com.iadams.plugins:gradle-sonar-packaging-plugin:0.1.4"

    }
}

repositories {
    maven {
        url "https://plugins.gradle.org/m2/"
    }
}

apply plugin: 'com.iadams.sonar-packaging'
dependencies {
    compile 'org.sonarsource.sonarqube:sonar-plugin-api:5.6'
}

```

But, after changing the `dependencies` section after reading your reply, it seems to correct the issue

```

dependencies {
    provided 'org.sonarsource.sonarqube:sonar-plugin-api:5.6'
}
```

**Comment by iwarapter** [comment]
Yes its a provided dependency not compile time.
